
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-metallb-com-v1-addresspool
  failurePolicy: Fail
  name: maddresspool.kb.io
  rules:
  - apiGroups:
    - app.metallb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-metallb-com-v1-addresspool
  failurePolicy: Fail
  name: vaddresspool.kb.io
  rules:
  - apiGroups:
    - app.metallb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
