# permissions to do viewer addresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addresspool-viewer-role
rules:
- apiGroups:
  - app.metallb.com
  resources:
  - addresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.metallb.com
  resources:
  - addresspools/status
  verbs:
  - get
