# permissions to do edit addresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addresspool-editor-role
rules:
- apiGroups:
  - app.metallb.com
  resources:
  - addresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.metallb.com
  resources:
  - addresspools/status
  verbs:
  - get
  - patch
  - update
